# Generated by Django 3.0 on 2019-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcrelyingparty',
            name='contacts',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
