# Generated by Django 3.1.1 on 2021-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcsession',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
