# Generated by Django 3.1.1 on 2021-03-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0002_auto_20210310_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcsession',
            old_name='uid',
            new_name='user_id',
        ),
    ]
