# Generated by Django 3.1.1 on 2021-03-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0003_auto_20210310_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcsession',
            old_name='user_id',
            new_name='user_uid',
        ),
    ]
