# Generated by Django 3.0 on 2019-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0003_auto_20191204_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcrelyingparty',
            name='auth_method',
            field=models.CharField(choices=[('client_secret_post', 'client_secret_post'), ('client_secret_basic', 'client_secret_basic'), (
                'client_secret_jwt', 'client_secret_jwt'), ('private_key_jwt', 'private_key_jwt')], default='client_secret_basic', max_length=33),
            preserve_default=False,
        ),
    ]
