# Generated by Django 3.1.1 on 2021-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0004_auto_20210310_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='grant',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
