# Generated by Django 3.0 on 2019-12-05 13:13

from django.db import migrations, models
import django.db.models.deletion
import oidcendpoint.sso_db


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0004_oidcrelyingparty_auth_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcEndpointSSOdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oidcendpoint.sso_db.SSODb),
        ),
        migrations.RemoveField(
            model_name='oidcrelyingparty',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='oidcrelyingparty',
            name='grant_types',
            field=models.CharField(choices=[('authorization_code', 'authorization_code'), ('implicit', 'implicit'), ('urn:ietf:params:oauth:grant-type:jwt-bearer', 'urn:ietf:params:oauth:grant-type:jwt-bearer'), ('refresh_token', 'refresh_token')], max_length=60),
        ),
        migrations.CreateModel(
            name='OidcRPContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcRelyingParty')),
            ],
            options={
                'verbose_name': 'Relying Party Contact',
                'verbose_name_plural': 'Relying Parties Contacts',
            },
        ),
    ]
