# Generated by Django 3.1.1 on 2021-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0005_oidcsession_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
