# Generated by Django 3.0 on 2019-12-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0005_auto_20191205_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcRPRedirectUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('redirect_uris', 'redirect_uris'), ('post_logout_redirect_uris', 'post_logout_redirect_uris')], max_length=33)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcRelyingParty')),
            ],
            options={
                'verbose_name': 'Relying Party URI',
                'verbose_name_plural': 'Relying Parties URIs',
            },
        ),
    ]
