# Generated by Django 3.0 on 2019-12-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0006_oidcrpredirecturis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcrelyingparty',
            name='grant_types',
        ),
        migrations.CreateModel(
            name='OidcRPGrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('grant_type', models.CharField(choices=[('authorization_code', 'authorization_code'), ('implicit', 'implicit'), ('urn:ietf:params:oauth:grant-type:jwt-bearer', 'urn:ietf:params:oauth:grant-type:jwt-bearer'), ('refresh_token', 'refresh_token')], max_length=60)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcRelyingParty')),
            ],
            options={
                'verbose_name': 'Relying Party GrantType',
                'verbose_name_plural': 'Relying Parties GrantTypes',
            },
        ),
    ]
