# Generated by Django 3.1.1 on 2021-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0006_oidcsession_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oidcsession',
            name='grant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
