# Generated by Django 3.1.1 on 2021-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0007_auto_20210310_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='grant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
