# Generated by Django 3.0 on 2019-12-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0007_auto_20191205_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcRPResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('authorization_code', 'authorization_code'), ('implicit', 'implicit'), ('urn:ietf:params:oauth:grant-type:jwt-bearer', 'urn:ietf:params:oauth:grant-type:jwt-bearer'), ('refresh_token', 'refresh_token')], max_length=60)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcRelyingParty')),
            ],
            options={
                'verbose_name': 'Relying Party Response Type',
                'verbose_name_plural': 'Relying Parties Response Types',
            },
        ),
    ]
