# Generated by Django 3.0 on 2019-12-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0008_oidcrpresponsetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oidcrpcontact',
            unique_together={('client', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='oidcrpgranttype',
            unique_together={('client', 'grant_type')},
        ),
        migrations.AlterUniqueTogether(
            name='oidcrpresponsetype',
            unique_together={('client', 'response_type')},
        ),
    ]
