# Generated by Django 3.0 on 2019-12-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0009_auto_20191205_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcrelyingparty',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='oidcrelyingparty',
            name='response_types',
        ),
    ]
