# Generated by Django 3.0 on 2019-12-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0010_auto_20191205_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcrpresponsetype',
            name='response_type',
            field=models.CharField(choices=[('code', 'code'), ('token', 'token'), ('id_token', 'id_token'), ('code token', 'code token'), ('code id_token', 'code id_token'), ('id_token token', 'id_token token'), ('code id_token token', 'code id_token token'), ('none', 'none')], max_length=60),
        ),
    ]
