# Generated by Django 3.0 on 2019-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0011_auto_20191205_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcrelyingparty',
            name='token_endpoint_auth_method',
            field=models.CharField(blank=True, choices=[('client_secret_post', 'client_secret_post'), ('client_secret_basic', 'client_secret_basic'), (
                'client_secret_jwt', 'client_secret_jwt'), ('private_key_jwt', 'private_key_jwt')], max_length=33, null=True),
        ),
    ]
