# Generated by Django 3.0 on 2019-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0012_auto_20191205_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcrelyingparty',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
