# Generated by Django 3.0 on 2019-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0013_oidcrelyingparty_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcrpredirecturis',
            name='values',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
