# Generated by Django 3.0 on 2019-12-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0014_oidcrpredirecturis_values'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OidcRPRedirectUris',
            new_name='OidcRPRedirectUri',
        ),
    ]
