# Generated by Django 3.0 on 2019-12-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_op', '0016_auto_20191206_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oidcendpointssodb',
            options={'verbose_name': 'SSO Session',
                     'verbose_name_plural': 'SSO Sessions'},
        ),
        migrations.AddField(
            model_name='oidcendpointssodb',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oidcendpointssodb',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oidcendpointssodb',
            name='user',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
