# Generated by Django 3.0 on 2019-12-09 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_op', '0018_oidcendpointssodb_sub_clean'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OidcEndpointSSOdb',
            new_name='OidcSession',
        ),
    ]
