# Generated by Django 3.0 on 2019-12-09 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_op', '0019_auto_20191209_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcsession',
            name='sid',
            field=models.CharField(default='asdasdasdasdasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oidcsession',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
