# Generated by Django 3.0 on 2019-12-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_op', '0020_auto_20191209_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcsession',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='oidcsession',
            name='sub_clean',
        ),
        migrations.RemoveField(
            model_name='oidcsession',
            name='user',
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='session_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oidcsession',
            name='state',
            field=models.CharField(
                default='asdasdas asd asd as', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OidcSessionSso',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sid', models.CharField(max_length=255)),
                ('sub', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_clean', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Session SSO',
                'verbose_name_plural': 'SSO Sessions SSO',
            },
        ),
    ]
