# Generated by Django 3.0 on 2019-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0021_auto_20191209_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcsession',
            name='sid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='oidcsessionsso',
            name='sid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
