# Generated by Django 3.0 on 2019-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0022_auto_20191209_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
