# Generated by Django 3.0 on 2019-12-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0024_auto_20191210_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcsession',
            name='sso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcSessionSso'),
        ),
    ]
