# Generated by Django 2.2.7 on 2019-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0025_auto_20191210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcrelyingparty',
            name='application_type',
            field=models.CharField(blank=True, default='web', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oidcrelyingparty',
            name='token_endpoint_auth_method',
            field=models.CharField(blank=True, choices=[('client_secret_post', 'client_secret_post'), ('client_secret_basic', 'client_secret_basic'), ('client_secret_jwt', 'client_secret_jwt'), ('private_key_jwt', 'private_key_jwt')], default='client_secret_basic', max_length=33, null=True),
        ),
    ]
