# Generated by Django 3.0 on 2019-12-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0026_auto_20191210_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcsessionsso',
            name='sub_clean',
        ),
    ]
