# Generated by Django 3.0 on 2020-07-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0027_remove_oidcsessionsso_sub_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcsessionsso',
            name='sid',
        ),
        migrations.CreateModel(
            name='OidcSessionSid',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('sso', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcSessionSso')),
            ],
        ),
    ]
