# Generated by Django 3.0 on 2020-07-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0028_auto_20200713_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcsessionsid',
            name='sso',
        ),
        migrations.AddField(
            model_name='oidcsessionsid',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcSession'),
            preserve_default=False,
        ),
    ]
