# Generated by Django 3.0 on 2020-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0029_auto_20200713_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
