# Generated by Django 3.0 on 2020-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0032_oidcsession_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OidcSessionSid',
        ),
    ]
