# Generated by Django 3.0 on 2020-07-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0033_auto_20200726_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcsession',
            name='sid',
        ),
        migrations.CreateModel(
            name='OidcSessionSid',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='oidc_op.OidcSession')),
            ],
        ),
    ]
