# Generated by Django 3.0 on 2020-07-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_op', '0034_auto_20200726_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OidcSessionSid',
        ),
    ]
