# Generated by Django 3.2.11 on 2022-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191202_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentid',
            name='persistent_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Persistent Stored ID'),
        ),
        migrations.AlterField(
            model_name='persistentid',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Relying-Party entityID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
